services:
  db:
    image: postgres:latest
    container_name: zap_forms_postgres
    restart: always
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: "db"
      POSTGRES_PORT: ${POSTGRES_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
  django-web:
    build: .
    container_name: zap_forms_django
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG}
      BACKEND_URL: ${BACKEND_URL}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
      DEFAULT_DJANGO_ADMIN_USER_EMAIL: ${DEFAULT_DJANGO_ADMIN_USER_EMAIL}
      DEFAULT_DJANGO_ADMIN_USER_USERNAME: ${DEFAULT_DJANGO_ADMIN_USER_USERNAME}
      DEFAULT_DJANGO_ADMIN_USER_PASSWORD: ${DEFAULT_DJANGO_ADMIN_USER_PASSWORD}
      DEFAULT_ADMIN_USER_EMAIL: ${DEFAULT_ADMIN_USER_EMAIL}
      DEFAULT_ADMIN_USER_USERNAME: ${DEFAULT_ADMIN_USER_USERNAME}
      DEFAULT_ADMIN_USER_PASSWORD: ${DEFAULT_ADMIN_USER_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: "db"
      POSTGRES_PORT: ${POSTGRES_PORT}
    env_file:
      - .env
volumes:
  postgres_data:
    driver: local
